name = "dosid"
compatibility_date = "2022-06-17"
workers_dev = true
usage_model = "bundled"
#route = { pattern = "*", zone_name = "example.com" }

main = "dist/index.mjs"

[vars]
DEBUG = false
DOSID_MAX_COUNT = 128

[build]
command = "yarn install && yarn test && yarn build"

[durable_objects]
bindings = [{name = "DOSID_COUNTER", class_name = "DOSIDCounter"}, {name = "DOSID_SHARDER", class_name = "DOSIDSharder"}]

[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["DOSIDCounter", "DOSIDSharder"]
